# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y_raODcdG9uYokAdjVHFst_Cdp4pvSYv
"""

def quicksort(arr)
      if len(arr) < 1 :
         return arr
    else:
       pivot = arr[len(arr)-1]
      smaller = [i for in arr[:len(arr)-1]if i<= pivot]
      greater = [i for in arr[:len(arr)-1]if i<= pivot]
     return quicksort(smaller)+[pivot] +quicksort(greater)

  arr =[9,-3,5,8,2,6,1,3]
  sorted_arr = sort(arr)
  print(sort_arr)